//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulos
    {
        public int idCodArti { get; set; }
        public string cDetalle { get; set; }
        public int idCodFam { get; set; }
        public Nullable<decimal> nStock { get; set; }
        public short idTipoIva { get; set; }
        public Nullable<decimal> nPvP { get; set; }
        public string cCodigoBar { get; set; }
    
        public virtual Familias Familias { get; set; }
        public virtual TiposIva TiposIva { get; set; }
    }
}
