//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public Clientes()
        {
            this.CABECERA_ALBAS = new HashSet<CABECERA_ALBAS>();
        }
    
        public int idCodCli { get; set; }
        public string cNomcli { get; set; }
        public string cDirCli { get; set; }
        public string cPobCli { get; set; }
        public string cTelefono1 { get; set; }
        public string cDniCif { get; set; }
        public string cContacto { get; set; }
        public string cCtaContable { get; set; }
        public Nullable<decimal> nDto { get; set; }
        public string cEmail { get; set; }
        public string cCodPostal { get; set; }
        public Nullable<System.DateTime> dFechaNaci { get; set; }
    
        public virtual ICollection<CABECERA_ALBAS> CABECERA_ALBAS { get; set; }
    }
}
