//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Familias
    {
        public Familias()
        {
            this.Articulos = new HashSet<Articulos>();
        }
    
        public int idCodFam { get; set; }
        public string cNombreFamilia { get; set; }
    
        public virtual ICollection<Articulos> Articulos { get; set; }
    }
}
