//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINEAS_ALBARAN
    {
        public int idOrdenLinea { get; set; }
        public int idNumAlba { get; set; }
        public int idCodArti { get; set; }
        public decimal nPvP { get; set; }
        public Nullable<decimal> nIva { get; set; }
        public Nullable<decimal> nDto { get; set; }
        public Nullable<decimal> nUnidades { get; set; }
        public Nullable<int> nOrden { get; set; }
    
        public virtual CABECERA_ALBAS CABECERA_ALBAS { get; set; }
    }
}
