//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VentasTOMASEntities : DbContext
    {
        public VentasTOMASEntities()
            : base("name=VentasTOMASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Articulos> Articulos { get; set; }
        public DbSet<CABECERA_ALBAS> CABECERA_ALBAS { get; set; }
        public DbSet<Clientes> Clientes { get; set; }
        public DbSet<CodiPos> CodiPos { get; set; }
        public DbSet<Entidad> Entidad { get; set; }
        public DbSet<Familias> Familias { get; set; }
        public DbSet<LINEAS_ALBARAN> LINEAS_ALBARAN { get; set; }
        public DbSet<Proveedores> Proveedores { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TiposIva> TiposIva { get; set; }
        public DbSet<Trabajadores> Trabajadores { get; set; }
    }
}
