//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposIva
    {
        public TiposIva()
        {
            this.Articulos = new HashSet<Articulos>();
        }
    
        public short idTipoIva { get; set; }
        public string cDetIva { get; set; }
        public Nullable<decimal> nPorcIva { get; set; }
        public Nullable<decimal> nPorReq { get; set; }
    
        public virtual ICollection<Articulos> Articulos { get; set; }
    }
}
