//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajadores
    {
        public int idTrabajador { get; set; }
        public string cNombreTraba { get; set; }
        public string cApellidos { get; set; }
        public string cAcceso { get; set; }
        public string Password { get; set; }
        public string cUsuario { get; set; }
    }
}
